# Generated by Django 5.0.4 on 2024-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_media_image_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='files', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Изображения'),
        ),
    ]
