# Generated by Django 5.0.4 on 2024-05-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_media_file_alter_media_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(default=None, max_length=5, verbose_name='Тип вложения'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='Файл'),
        ),
    ]
